version: 2.1
workflows:
  build_test:
    jobs:
      - build:
          version: "5.6"
      - build:
          version: "7.1"
      - build:
          version: "7.2"
jobs:
  build:
    parameters:
      version:
        type: string
    environment:
      PHPUNIT_ARGS: ""
      TERM: dumb
      TZ: "/usr/share/zoneinfo/America/Los_Angeles"
      UNISH_DB_URL: mysql://root:@127.0.0.1
      UNISH_NO_TIMEOUTS: y
      PHP_VER: << parameters.version >>
    docker:
      - image: wodby/php:<< parameters.version >>
        environment:
          - MYSQL_HOST=127.0.0.1
          - PHP_SENDMAIL_PATH=/dev/null
      - image: circleci/mysql:5.7.24
    steps:
      - checkout
      - run: cp .docker/zz-php.ini /usr/local/etc/php/conf.d/
      - run: |
          if [ $PHP_VER = "5.6" ]; then
            .scenarios.lock/install php5
            .circleci/patch.sh
          elif [ $PHP_VER = "7.1" ]; then
            .circleci/patch.sh
            composer install
          elif [ $PHP_VER = "7.2" ]; then
            composer remove --dev webflo/drupal-core-strict --no-update
            composer require --dev drupal/core:8.7.x-dev --no-update
            composer config platform.php 7.2
            composer install
          fi
      - run: composer functional
